version: "3"
services:
  tg-neuramark-bot:
    build: .
    restart: always
    volumes:
      - ./app:/app
    logging:
      driver: "json-file"
      options:
          max-size: "2m"
          max-file: "10"
    environment:
      - API_TOKEN=TG_TOKEN
      - NEURAMARK_TOKEN=TOKEN
      - BACKEND_API_URL=BACKEND_URL
